apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: rabbit-management
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: rabbit.dev.local
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq-client
          servicePort: 15672
